# Generated by Django 5.0.7 on 2024-07-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_privileges_accesspages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessPages',
        ),
        migrations.DeleteModel(
            name='Privileges',
        ),
    ]
